apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-operators-catalog
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"catalogs:community-operators"},"fieldPath":"spec.template.spec.containers[?(@.name==\"registry\")].image"}]'
spec:
  selector:
    matchLabels:
      olm.catalogSource: community-operators
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        olm.catalogSource: community-operators
        app: community-operators-catalog
        hypershift.openshift.io/control-plane-component: community-operators-catalog
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: registry
          image: catalogs:community-operators
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 15
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
