apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: admission-tracer-serving-cert
  labels:
    app: admission-tracer
  name: admission-tracer
  namespace: hypershift
spec:
  ports:
  - name: manager
    port: 443
    protocol: TCP
    targetPort: manager
  selector:
    app: admission-tracer
  type: ClusterIP
